### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by PayasR**
1. Fixed a typo in the project_name in src/CMakeLists.txt
2. Git external module googlelog does not download the Configure file for CONFIGURE_STEP and fails to compile. Also, CONFIGURE_STEP isn't really required! let CMake handle the compilation.

### CODE REVIEW

**Comment by mwhittaker** [comment]
Hi @PayasR, thanks so much for the pull request! When I try to build the code with this pull request, I get the following error message. 

```
[ 80%] Building CXX object client/CMakeFiles/client.dir/client.cc.o
/tmp/cpp_project_template/src/client/client.cc:7:10: fatal error: 'glog/logging.h' file not
      found
#include "glog/logging.h"
         ^
1 error generated.
```

Running `ls build/vendor/googlelog/src/googlelog/src/glog/`, I don't find a `logging.h` file. If I change the `CONFIGURE_COMMAND` to `CONFIGURE_COMMAND ./autogen.sh && ./configure`, then everything compiles normally. Does the same thing happen for you?

**Comment by PayasR** [comment]
That's interesting! 
Can you please check what files are downloaded in the build/vendor/googlelog? I'm getting an error with the base code because it doesn't download the ./autogen.sh file at all.
```
➜  googlelog git:(master) ls -alh
total 32K
drwxr-xr-x. 5 payas payas 4.0K Jun 11 00:55 .
drwxr-xr-x. 7 payas payas 4.0K Jun 11 00:52 ..
drwxr-xr-x. 3 payas payas 4.0K Jun 11 00:55 CMakeFiles
-rw-r--r--. 1 payas payas 1022 Jun 11 00:52 cmake_install.cmake
-rw-r--r--. 1 payas payas 5.1K Jun 11 00:52 Makefile
drwxr-xr-x. 4 payas payas 4.0K Jun 11 00:52 src
drwxr-xr-x. 2 payas payas 4.0K Jun 11 00:55 tmp
```
And the error is:
```
[ 15%] Creating directories for 'googlelog'
[ 17%] Performing download step (git clone) for 'googlelog'
Cloning into 'googlelog'...
Already on 'master'
Your branch is up-to-date with 'origin/master'.
[ 19%] No patch step for 'googlelog'
[ 21%] No update step for 'googlelog'
[ 22%] Performing configure step for 'googlelog'
/bin/sh: ./configure: No such file or directory
gmake[2]: *** [vendor/googlelog/CMakeFiles/googlelog.dir/build.make:107: vendor/googlelog/src/googlelog-stamp/googlelog-configure] Error 127
gmake[1]: *** [CMakeFiles/Makefile2:141: vendor/googlelog/CMakeFiles/googlelog.dir/all] Error 2
gmake: *** [Makefile:95: all] Error 2
```
Also, if I may ask, why does the code depend on downloading and building zeromq and googletest? Shouldn't they be just dependencies that are installed through the system package manager?

**Comment by shaneknapp** [comment]
i'll chime in really quick (as i'm the build engineer for the lab):

we currently have the libzmq3-dev package installed, and a locally built
version of jzmq (3.1.1).

if we're ok w/3.1.0, i can install those packages and remove the 3.1.1 dist
on the workers.

as for googletest, there's no debian package for 16.04LTS.

shane

**Comment by mwhittaker** [comment]
@PayasR, I've attached a file with the entire contents of `build/vendor/googlelog`. The `googlelog` repo just recently added the `autogen.sh` script. Try deleting the `build` directory completely and building again? 

As for why have dependencies installed via CMake as opposed to assuming they're built by a system package manager. No big reason; I think they're both fine. The CMake way just makes it a tiny bit easier to get the code building without having to run a bunch of other stuff. 

@shaneknapp, feel free to install those packages and remove the 3.1.1 dist on the workers! I think this stuff will build fine either way.

[out.txt](https://github.com/ucbrise/cpp_project_template/files/1072442/out.txt)

**Comment by shaneknapp** [comment]
@mwhittaker -- i spoke to @dcrankshaw  in the lab and he'd like to do some testing before i wipe the handrolled libs.

**Comment by mwhittaker** [comment]
@shaneknapp, okay no worries!

**Comment by PayasR** [comment]
Thanks a ton @mwhittaker! I got it working with the ```CONFIGURE_COMMAND ./autogen.sh && ./configure```, though the build broke due to libtool not being available on my machine. You should add it as a dependency somewhere, but it works. Thank you :)

**Comment by mwhittaker** [comment]
@PayasR Sweet! Ah yes, good catch on the `libtool` thing. If you add `CONFIGURE_COMMAND ./autogen.sh && ./configure` to this pull request and maybe mention `libtool` in a README somewhere, I'd be more than happy to merge in your pull request! I can do it too, if you're busy :)

**Comment by mwhittaker** [comment]
@PayasR thanks a million for the pull request!

**Comment by PayasR** [comment]
@mwhittaker Happy to help :)
The markdown on the README is slightly screwed up. Can you please get it from my branch?

**Comment by mwhittaker** [comment]
Done!

**Pull request merged**
